# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Waji Blog
SEOTitle: Jason Wang | Waji Blog
email: jason.jc.wang@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://coolgenerator.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# SNS settings
RSS: false
# twitter_username: jekyllrb
github_username:  coolgenerator
github_repo: "https://github.com/coolgenerator/coolgenerator.github.io"
linkedin_username: jiw196
zhihu_username: wan-ju-che-wan-ju-che

# Publish posts or collection documents with a future date.
future: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

highlighter: rouge
permalink: /:year/:month/:day/:title/
# permalink: pretty
paginate: 10
paginate_path: "/blog/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true

page-mathjax: 
  enable: true

# Sidebar settings
sidebar:
  - title: About
    path: /about
  - title: Archive
    path: /archive
  - title: Categories
    path: /categories
  - title: Tags
    path: /tags


# gitalk
gitalk:
  enable: true    
  clientID: Ov23liP9yGFbRExNKl9r                          
  clientSecret: a0992c1a31ba36bed8d60435ef288bd68a44a0bf  
  repo: coolgenerator.github.io    
  owner: coolgenerator    
  admin: coolgenerator
  distractionFreeMode: false
  language: [en, zh-CN]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

imagemagick:
  enabled: true
  widths:
    - 1024
    - 512
    - 0
  input_directories:
    - assets/files
  input_formats:
    - ".png"
    - ".tiff"
  output_formats:
    jpg: "-quality 93% -define jpeg:dct-method=float -strip -interlace Plane"
    webp: "-quality 100%"